@extends('admin.layout')
@section('content')
<x-admin.page-header title="Data Petugas" subtitle="Kelola petugas harian dan jadwal piket" :breadcrumbs="['Datapedia','Layanan','Petugas']" addRoute="{{route('petugas.create')}}" addLabel="Tambah Petugas" />
<div class="card" style="background:#fff;border:0.5px solid #e2e8f0;border-radius:12px;overflow:hidden">
    <div style="padding:14px 18px;border-bottom:0.5px solid #e2e8f0;display:flex;align-items:center;flex-wrap:wrap;justify-content:space-between;gap:10px">
        <div style="font-size:13px;font-weight:600;color:#0f172a;display:flex;align-items:center;gap:8px"><i class="ti ti-calendar-week" style="font-size:16px;color:#1F6FD6"></i>Daftar Petugas</div>
        <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
            <form action="{{route('petugas.index')}}" method="GET" style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
                <input type="date" name="tanggal" value="{{request('tanggal')}}" style="height:32px;padding:0 8px;border:0.5px solid #e2e8f0;border-radius:6px;font-size:11px;color:#0f172a;outline:none;background:#fff">
                <select name="bulan" style="height:32px;padding:0 8px;border:0.5px solid #e2e8f0;border-radius:6px;font-size:11px;color:#0f172a;outline:none;background:#fff"><option value="">Bulan</option>@foreach(range(1,12) as $b)<option value="{{$b}}" {{request('bulan')==$b?'selected':''}}>{{\Carbon\Carbon::create(null,$b)->locale('id')->isoFormat('MMMM')}}</option>@endforeach</select>
                <select name="tahun" style="height:32px;padding:0 8px;border:0.5px solid #e2e8f0;border-radius:6px;font-size:11px;color:#0f172a;outline:none;background:#fff"><option value="">Tahun</option>@for($i=date('Y');$i>=2024;$i--)<option value="{{$i}}" {{request('tahun')==$i?'selected':''}}>{{$i}}</option>@endfor</select>
                <button type="submit" style="display:inline-flex;align-items:center;gap:4px;padding:5px 10px;background:#f8fafc;border:0.5px solid #e2e8f0;border-radius:6px;font-size:11px;font-weight:500;color:#0f172a;cursor:pointer">Filter</button>
                <a href="{{route('petugas.index')}}" style="font-size:11px;color:#64748b;text-decoration:none">Reset</a>
            </form>
            <a href="{{route('petugas.export-pdf',request()->all())}}" style="display:inline-flex;align-items:center;gap:4px;padding:5px 10px;background:#EEEDFE;color:#534AB7;border-radius:6px;font-size:11px;font-weight:500;text-decoration:none"><i class="ti ti-download" style="font-size:12px"></i>PDF</a>
        </div>
    </div>
    <div style="overflow-x:auto">
        <table style="width:100%;border-collapse:collapse">
            <thead><tr style="background:#f8fafc"><th style="padding:10px 16px;text-align:center;width:48px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">No</th><th style="padding:10px 16px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Petugas</th><th style="padding:10px 16px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Tanggal</th><th style="padding:10px 16px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Aksi</th></tr></thead>
            <tbody>@forelse($petugas as $idx => $item)<tr style="transition:background 100ms" onmouseover="this.style.background='#f8fafc'" onmouseout="this.style.background=''"><td style="padding:12px 16px;font-size:11px;color:#94a3b8;border-bottom:0.5px solid #e2e8f0;text-align:center">{{$idx+1}}</td><td style="padding:12px 16px;font-size:12px;font-weight:600;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{$item->konsultan->nama}}</td><td style="padding:12px 16px;font-size:12px;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{\Carbon\Carbon::parse($item->tanggal)->locale('id')->isoFormat('D MMMM Y')}}</td><td style="padding:12px 16px;border-bottom:0.5px solid #e2e8f0"><div style="display:flex;gap:5px"><a href="{{route('petugas.edit',$item->id)}}" style="display:inline-flex;align-items:center;gap:4px;padding:4px 9px;background:#E6F1FB;color:#0C447C;border-radius:6px;font-size:11px;font-weight:500;text-decoration:none" onmouseover="this.style.background='#B5D4F4'" onmouseout="this.style.background='#E6F1FB'"><i class="ti ti-edit" style="font-size:12px"></i>Edit</a><form action="{{route('petugas.destroy',$item->id)}}" method="POST" style="margin:0"><button type="submit" onclick="return confirm('Hapus?')" style="display:inline-flex;align-items:center;gap:4px;padding:4px 9px;background:#FCEBEB;color:#791F1F;border:none;border-radius:6px;font-size:11px;font-weight:500;cursor:pointer" onmouseover="this.style.background='#F7C1C1'" onmouseout="this.style.background='#FCEBEB'"><i class="ti ti-trash" style="font-size:12px"></i>Hapus</button>@csrf @method('DELETE')</form></div></td></tr>@empty<tr><td colspan="4" style="padding:40px;text-align:center;color:#94a3b8;font-size:13px">Belum ada data petugas</td></tr>@endforelse</tbody>
        </table>
    </div>
    <div style="padding:10px 16px;border-top:0.5px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between"><span style="font-size:11px;color:#64748b">Menampilkan {{count($petugas)}} data</span></div>
</div>
@endsection