@extends('admin.layout')
@section('content')
<x-admin.page-header title="Pesan Masuk WA" subtitle="Pesan konsultasi yang masuk melalui WhatsApp" :breadcrumbs="['Datapedia','FAQ','Pesan WA']" />
<div class="card" style="background:#fff;border:0.5px solid #e2e8f0;border-radius:12px;overflow:hidden">
    <div style="padding:14px 18px;border-bottom:0.5px solid #e2e8f0">
        <div style="font-size:13px;font-weight:600;color:#0f172a;display:flex;align-items:center;gap:8px"><i class="ti ti-message" style="font-size:16px;color:#1F6FD6"></i>Daftar Pesan <span style="font-size:11px;font-weight:400;color:#94a3b8;margin-left:4px">— {{count($faq)}} data</span></div>
    </div>
    <div style="overflow-x:auto">
        <table style="width:100%;border-collapse:collapse;min-width:1100px">
            <thead><tr style="background:#f8fafc"><th style="padding:10px 8px;text-align:center;width:32px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">No</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Tanggal</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Nama</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">No WA</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Instansi</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Data Diminta</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Posisi</th><th style="padding:10px 8px;font-size:10px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Aksi</th></tr></thead>
            <tbody>@forelse($faq as $idx=>$i)<tr style="transition:background 100ms" onmouseover="this.style.background='#f8fafc'" onmouseout="this.style.background=''"><td style="padding:10px 8px;font-size:11px;color:#94a3b8;border-bottom:0.5px solid #e2e8f0;text-align:center">{{$idx+1}}</td><td style="padding:10px 8px;font-size:11px;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{\Carbon\Carbon::parse($i->clicked_at)->locale('id')->isoFormat('D MMM Y, HH:mm')}}</td><td style="padding:10px 8px;font-size:11px;font-weight:600;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{$i->user->nama??'-'}}</td><td style="padding:10px 8px;font-size:11px;color:#64748b;border-bottom:0.5px solid #e2e8f0;font-family:monospace">{{$i->user->no_hp??'-'}}</td><td style="padding:10px 8px;font-size:11px;color:#0f172a;border-bottom:0.5px solid #e2e8f0;max-width:130px">{{$i->instansi}}</td><td style="padding:10px 8px;font-size:11px;color:#475569;border-bottom:0.5px solid #e2e8f0;max-width:150px">{{Str::limit($i->data_diminta,40)}}</td><td style="padding:10px 8px;font-size:11px;color:#0f172a;border-bottom:0.5px solid #e2e8f0">@php $lp=['asn'=>'ASN','karyawan_swasta'=>'Karyawan','wiraswasta'=>'Wiraswasta','peneliti'=>'Peneliti','pelajar_mahasiswa'=>'Mahasiswa','lainnya'=>'Lainnya'];@endphp{{$lp[$i->posisi]??$i->posisi}}</td><td style="padding:10px 8px;border-bottom:0.5px solid #e2e8f0"><form action="{{route('faq.hapusPesan',$i->id)}}" method="POST" style="margin:0"><button type="submit" onclick="return confirm('Hapus?')" style="display:inline-flex;align-items:center;gap:3px;padding:3px 8px;background:#FCEBEB;color:#791F1F;border:none;border-radius:5px;font-size:10px;font-weight:500;cursor:pointer"><i class="ti ti-trash" style="font-size:11px"></i>Hapus</button>@csrf @method('DELETE')</form></td></tr>@empty<tr><td colspan="8" style="padding:40px;text-align:center;color:#94a3b8;font-size:13px">Belum ada pesan konsultasi masuk</td></tr>@endforelse</tbody>
        </table>
    </div>
    <div style="padding:10px 16px;border-top:0.5px solid #e2e8f0"><span style="font-size:11px;color:#64748b">Menampilkan {{count($faq)}} data</span></div>
</div>
@endsection