@extends('admin.layout')
@section('content')
@php
use App\Models\Konsultan;use Illuminate\Support\Carbon;
$notifikasiKonsultan = Konsultan::where('status','tidak tersedia')->whereNotNull('status_updated_at')->where('status_updated_at','>=',Carbon::now()->subDays(30))->get();
@endphp
<x-admin.page-header title="Data Konsultan" subtitle="Kelola konsultan statistik dan bidang keahliannya" :breadcrumbs="['Datapedia','Manajemen User','Konsultan']" addRoute="{{route('konsultan.create')}}" addLabel="Tambah Konsultan" />
@if($notifikasiKonsultan->count())
<div style="background:#FAEEDA;border:1px solid #FAC775;color:#633806;padding:12px 16px;border-radius:10px;font-size:12px;display:flex;align-items:flex-start;gap:8px"><i class="ti ti-alert-triangle" style="font-size:15px;flex-shrink:0;margin-top:2px"></i><div><strong>Notifikasi:</strong> Ada {{$notifikasiKonsultan->count()}} konsultan tidak tersedia dalam 30 hari terakhir: {{$notifikasiKonsultan->pluck('nama')->join(', ')}}</div></div>
@endif
<div class="card" style="background:#fff;border:0.5px solid #e2e8f0;border-radius:12px;overflow:hidden">
    <div style="padding:14px 18px;border-bottom:0.5px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between">
        <div style="font-size:13px;font-weight:600;color:#0f172a;display:flex;align-items:center;gap:8px"><i class="ti ti-tie" style="font-size:16px;color:#1F6FD6"></i>Daftar Konsultan <span style="font-size:11px;font-weight:400;color:#94a3b8;margin-left:4px">— {{count($konsultan)}} data</span></div>
    </div>
    <div style="overflow-x:auto">
        <table style="width:100%;border-collapse:collapse;min-width:1100px">
            <thead><tr style="background:#f8fafc"><th style="padding:10px 12px;text-align:center;width:40px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">No</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Nama</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Email</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Posisi</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Keahlian</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Status</th><th style="padding:10px 12px;font-size:11px;font-weight:600;color:#64748b;border-bottom:0.5px solid #e2e8f0;text-transform:uppercase">Aksi</th></tr></thead>
            <tbody>@php $no=1;@endphp
            @forelse($konsultan as $item)<tr style="transition:background 100ms" onmouseover="this.style.background='#f8fafc'" onmouseout="this.style.background=''"><td style="padding:10px 12px;font-size:11px;color:#94a3b8;border-bottom:0.5px solid #e2e8f0;text-align:center">{{$no++}}</td>
            <td style="padding:10px 12px;font-size:12px;font-weight:600;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{$item->nama}}</td>
            <td style="padding:10px 12px;font-size:11px;color:#64748b;border-bottom:0.5px solid #e2e8f0;font-family:monospace">{{$item->email}}</td>
            <td style="padding:10px 12px;font-size:12px;color:#0f172a;border-bottom:0.5px solid #e2e8f0">{{$item->posisi}}</td>
            <td style="padding:10px 12px;border-bottom:0.5px solid #e2e8f0">@if($item->bidangKeahlian->count())<div style="display:flex;flex-wrap:wrap;gap:3px">@foreach($item->bidangKeahlian as $b)<span style="display:inline-flex;padding:2px 7px;border-radius:999px;font-size:10px;font-weight:500;background:#E6F1FB;color:#0C447C">{{$b->nama_bidang}}</span>@endforeach</div>@else<span style="font-size:11px;color:#94a3b8">-</span>@endif</td>
            <td style="padding:10px 12px;border-bottom:0.5px solid #e2e8f0">@if($item->status=='tersedia')<span style="display:inline-flex;align-items:center;gap:4px;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:500;background:#EAF3DE;color:#27500A"><span style="width:6px;height:6px;border-radius:50%;background:#3B6D11;display:inline-block"></span>Tersedia</span>@else<span style="display:inline-flex;align-items:center;gap:4px;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:500;background:#FCEBEB;color:#791F1F"><span style="width:6px;height:6px;border-radius:50%;background:#E24B4A;display:inline-block"></span>Tidak Tersedia</span>@endif</td>
            <td style="padding:10px 12px;border-bottom:0.5px solid #e2e8f0"><div style="display:flex;gap:5px"><a href="{{route('konsultan.edit',$item->id)}}" style="display:inline-flex;align-items:center;gap:4px;padding:4px 9px;background:#E6F1FB;color:#0C447C;border-radius:6px;font-size:11px;font-weight:500;text-decoration:none;transition:background 120ms" onmouseover="this.style.background='#B5D4F4'" onmouseout="this.style.background='#E6F1FB'"><i class="ti ti-edit" style="font-size:12px"></i>Edit</a><form action="{{route('konsultan.destroy',$item->id)}}" method="POST" style="margin:0"><button type="submit" onclick="return confirm('Hapus data ini?')" style="display:inline-flex;align-items:center;gap:4px;padding:4px 9px;background:#FCEBEB;color:#791F1F;border:none;border-radius:6px;font-size:11px;font-weight:500;cursor:pointer;transition:background 120ms" onmouseover="this.style.background='#F7C1C1'" onmouseout="this.style.background='#FCEBEB'"><i class="ti ti-trash" style="font-size:12px"></i>Hapus</button>@csrf @method('DELETE')</form></div></td></tr>@empty<tr><td colspan="7" style="padding:40px;text-align:center;color:#94a3b8;font-size:13px">Belum ada data konsultan</td></tr>@endforelse</tbody>
        </table>
    </div>
    <div style="padding:10px 16px;border-top:0.5px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between"><span style="font-size:11px;color:#64748b">Menampilkan {{count($konsultan)}} data</span></div>
</div>
@endsection